name: 'QuickJS Test Runner'
description: 'QuickJS (qjs) Test Runner'
inputs:
  mainFile:
    description: 'Main script to run/compile'
    required: true
    default: 'main.js'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.mainFile }}
